### ISSUE TITLE
Update typings with new props

### ISSUE THREAD

**Issue by katalonne** [Norserium/react-indiana-drag-scroll#34]
`stopPropagation` missing

**Comment by Norserium** [comment]
@katalonne, it's undocumented also. But I'm glad to see someone, who want to use it. Could you describe the case?

**Comment by katalonne** [comment]
@Norserium ahh.. I thought it will disable the drag...
I'm implementing a hand tool and I need to disable the drag.
Thanks for the reply.

**Comment by Norserium** [comment]
> I'm implementing a hand tool and I need to disable the drag.

Disable drag?

**Comment by katalonne** [comment]
`onMouseMove`

**Comment by Norserium** [comment]
Sorry, but I don't understand. If it would be helpful, I know Russian also. There is high probability, that you know it too.

**Comment by katalonne** [comment]
Mne inogda ne nado scroll kogda `drag (cerez mouse click)`, toliko na `mousewheel`.
caroce tam esti functia : `isDraggable`, i napisal kostyli )

```
(ScrollContainer.prototype as any).isDraggable = function (target: any) {
  const { ignoreElements, disableDrag } = this.props
  if (disableDrag) return false
  if (ignoreElements) {
    const closest = target.closest(ignoreElements)
    return closest === null || closest.contains(this.getElement())
  } else {
    return true
  }
}
```

Tipa dobavil novyi prop: `disableDrag`

**Comment by Norserium** [comment]
The same effect you may get by adding the following prop: `ignoreElements={disableDrag ? "*" : ""}`. But it's pretty strange case, in the described situation I don't see the reason to use this library. It's designed to implement scroll by mouse.
<details>
<summary>
Перевод на русский
</summary>
Аналогичный эффект можно получить добавлением пропса: <pre>ignoreElements={disableDrag ? "*" : ""}</pre> Но это довольно странный кейс, поскольку в описанной ситуации я не вижу смысла использовать эту библиотеку. Она предназначена для прокручивания мышкой.
</details>

**Comment by katalonne** [comment]
> I don't see the reason to use this library

As I said: `I'm implementing a hand tool and I need to disable the drag`
I have to modes, think `canDrag: boolean`.

**Comment by Norserium** [comment]
What's "hand tool"?

<details>
<summary>
Перевод на русский
</summary>
А что за "hand tool"?
</details>

**Comment by katalonne** [comment]
@Norserium https://answers.acrobatusers.com/How-I-access-hand-tool-Adobe-Reader-q151155.aspx

**Comment by katalonne** [comment]
`ignoreElements={disableDrag ? "*" : ""}` thanks!

**Comment by Norserium** [comment]
I suppose, that solution above is pretty suitable for this situation. Not obvious, but not weird. But you should notice that it will not disable dragging on mobile devices.

I will think about `disabled` prop, but it's arguable solution, because it's not obvious what's exactly will be disabled (drag scroll, every scroll and etc.)

<details>
<summary>
Перевод на русский
</summary>
Я думаю, решение, приведённое выше, вполне подходит для данной ситуации. Не очевидное, но и не столь костыльное. Однако следует отметить, что оно не отключит соответствующий скроллинг для мобильных устройств.


Я подумаю насчёт добавления пропса "disabled", но это достаточно спорное решение, поскольку не вполне очевидно, что именно будет отключено (скролл мышкой, любой скролл и т.д.)
</details>

**Comment by katalonne** [comment]
> what's exactly will be disabled

You can document the `disabled` prop as `Disable drag on desktop browsers `.
