### ISSUE TITLE
Change input in container

### ISSUE THREAD

**Issue by phanquanDHTB** [Norserium/react-indiana-drag-scroll#71]
i have input in container and i can't change value input. it seems container was block change input.  i need a solution, thank everyone
i using google translate

**Comment by Norserium** [comment]
@phanquanDHTB, you can use [the following workaround](https://codesandbox.io/s/react-indiana-drag-scroll-input-workaround-o479rc). The next major version that is currently in the development should resolve this issue natively.

**Comment by phanquanDHTB** [comment]
@Norserium thank you so much <3

**Comment by Norserium** [comment]
@phanquanDHTB, you are welcome!

**Comment by Norserium** [comment]
@phanquanDHTB, this issue is resolved in [`3.x.x`](https://norserium.github.io/react-indiana-drag-scroll/), but still you need to pass `"input"` to `ignoreElements`, because the because the cursor still will be intercepted by the container. That's how scroll works.

[The example](https://norserium.github.io/react-indiana-drag-scroll/docs/recipes#inputs).
